# Generated by Django 6.1.1 on 2026-09-14 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_names', models.CharField(max_length=150)),
                ('family_name', models.CharField(max_length=150)),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('orcid', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['family_name', 'given_names'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('archived', 'Archived')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_programmes', to='portal.person')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pi', 'PI'), ('researcher', 'Researcher'), ('admin', 'Programme Admin')], default='researcher', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_memberships', to='portal.person')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='portal.researchprogramme')),
            ],
            options={
                'ordering': ['programme__name', 'person__family_name'],
                'constraints': [models.UniqueConstraint(fields=('programme', 'person'), name='unique_programme_membership')],
            },
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('fingerprint', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to='portal.person')),
            ],
            options={
                'ordering': ['person__family_name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('person', 'name'), name='unique_ssh_key_name_per_person')],
            },
        ),
        migrations.CreateModel(
            name='WireGuardKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wireguard_keys', to='portal.person')),
            ],
            options={
                'ordering': ['person__family_name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('person', 'name'), name='unique_wireguard_key_name_per_person')],
            },
        ),
    ]
